# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-01-23 11:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_app', '0002_samplemodel'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='samplemodel',
            new_name='Sample',
        ),
    ]
